Genepop  version 4.0.9: Hardy-Weinberg test

File: Aclarkii_GenAlEx_2009-03-09.txt (Title line:"Aclarkii 3 regions")

Number of populations detected:    1
Number of loci detected:           13


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     100
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote excess
                         ***********************



==========================================
     Results by population
==========================================


 Pop : NA
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
AC1359      0.9988  0.0004   0.0315  0.1198  84507 switches
AC1578      0.9988  0.0003   0.1184  0.0956 229127 switches
AC915       0.5722  0.0057  -0.0111 -0.0159  38923 switches
ACH_B6      0.3380  0.0182  -0.0105 -0.0067 130964 switches
ACH_C1      0.6998  0.0137   0.0020  0.0071 159708 switches
ACH_D1      0.5893  0.0230   0.0100  0.0001  62053 switches
APR_Cf29    0.9607  0.0045   0.0734  0.0309  65786 switches
APR_Cf8     0.8760  0.0041   0.0313  0.0414 390012 switches
APY_45      0.5404  0.0245   0.0359  0.0013  36039 switches
APY_65      0.9572  0.0041   0.0124  0.0314 114819 switches
NNG_004     0.8074  0.0045   0.0390  0.0157 109287 switches
NNG_012     0.8238  0.0059   0.0520  0.0267 236908 switches
NNG_028     0.7351  0.0206   0.0289  0.0042  32472 switches

Normal ending