Genepop  version 4.0.9: Hardy-Weinberg test

File: Aclarkii_GenAlEx_2009-03-09.txt (Title line:"Aclarkii 3 regions")

Number of populations detected:    1
Number of loci detected:           13


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     100
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


 Pop : NA
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
AC1359      0.0012  0.0003   0.0315  0.1198  84245 switches
AC1578      0.0010  0.0002   0.1184  0.0956 228691 switches
AC915       0.6504  0.0058  -0.0111 -0.0159  39152 switches
ACH_B6      0.6723  0.0177  -0.0105 -0.0067 131134 switches
ACH_C1      0.3362  0.0135   0.0020  0.0071 160127 switches
ACH_D1      0.4978  0.0264   0.0100  0.0001  61939 switches
APR_Cf29    0.0334  0.0043   0.0734  0.0309  65824 switches
APR_Cf8     0.1340  0.0049   0.0313  0.0414 390127 switches
APY_45      0.3560  0.0196   0.0359  0.0013  35741 switches
APY_65      0.0609  0.0052   0.0124  0.0314 114473 switches
NNG_004     0.2340  0.0054   0.0390  0.0157 109582 switches
NNG_012     0.1846  0.0066   0.0520  0.0267 236473 switches
NNG_028     0.2222  0.0176   0.0289  0.0042  31642 switches

Normal ending