Genepop  version 4.0.9: Hardy-Weinberg test

File: Aclarkii_2009-03-13.txt (Title line:"Aclarkii onepop")

Number of populations detected:    1
Number of loci detected:           14


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


 Pop : NA
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
AC1359      0.0017  0.0008   0.0384  0.1210  17203 switches
AC1578      0.0019  0.0007   0.1184  0.0956  46064 switches
AC915       0.6453  0.0084  -0.0112 -0.0160   7692 switches
ACH_A7      0.0000  0.0000   0.3238  0.1957  18555 switches
ACH_B6      0.6203  0.0457  -0.0105 -0.0067  26202 switches
ACH_C1      0.3479  0.0322   0.0020  0.0071  31981 switches
ACH_D1      0.3726  0.0558   0.0107  0.0002  12465 switches
APR_Cf29    0.9405  0.0230  -0.0281 -0.0133   8233 switches
APR_Cf8     0.1094  0.0100   0.0328  0.0426  77956 switches
APY_45      0.2969  0.0391   0.0296 -0.0004   6980 switches
APY_65      0.1426  0.0208  -0.0110  0.0110   6365 switches
NNG_004     0.2295  0.0134   0.0390  0.0157  21926 switches
NNG_012     0.2107  0.0153   0.0520  0.0267  47503 switches
NNG_028     0.2881  0.0287   0.0298  0.0041   5107 switches

Normal ending